### ISSUE TITLE
xxhash_module not found

### ISSUE THREAD

**Issue by arcoirislabs** [pierrec/node-lz4#24]
After installing the lz4 from npm, no errors are seen. When used in project shows following error
Error: Symbol xxhash_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\ad-ad\xx-xxx\node_modules\lz4\lib\utils.js:4:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Env - Windows 7 (64 bit), Node - v0.10.31

Any prob with my env or the module?

**Comment by pierrec** [comment]
Hello,

I have never tested this on windows. But it looks like the module did not get compiled for some reason? npm should have done that upon installation...
If I get hold of a windows machine, I will test this.

**Comment by arcoirislabs** [comment]
Thanks.

**Comment by pierrec** [comment]
Sorry for the very late reply.

It seems you cloned from github directly without installing via npm.
In this case you need to do the following extra steps:

npm i
node-gyp rebuild

**Comment by arcoirislabs** [comment]
Thank you Mr. Curto for solving the issue. We will try the the solution. Cheers

-----Original Message-----
