### ISSUE TITLE
CentOS 7 with Node.js 13.6.0 installation failed

### ISSUE THREAD

**Issue by aeroxy** [pierrec/node-lz4#90]
Linux 3.10.0-514.21.1.el7.x86_64

```
635 verbose stack Exit status 1
635 verbose stack     at EventEmitter.<anonymous> (/data/node-v13.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
635 verbose stack     at EventEmitter.emit (events.js:321:20)
635 verbose stack     at ChildProcess.<anonymous> (/data/node-v13.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
635 verbose stack     at ChildProcess.emit (events.js:321:20)
635 verbose stack     at maybeClose (internal/child_process.js:1028:16)
635 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
636 verbose pkgid lz4@0.6.3
```

```
640 verbose node v13.6.0
641 verbose npm  v6.13.4
642 error code ELIFECYCLE
643 error errno 1
```

**Comment by aeroxy** [comment]
I think it has little to do with the version of Node.js tho... I am going to try to see if make LZ4 would fail on this machine sometime tmr.

**Comment by aeroxy** [comment]
Never mind, I realized I didn't install gcc and gcc-c++ on this machine.
