### ISSUE TITLE
Corrupt package?

### ISSUE THREAD

**Issue by buu700** [pierrec/node-lz4#92]
Installing 0.6.2 or 0.6.3 with Node 12.16.1 and yarn 1.22.1 on Debian 10.3 fails for me:

```
gibson@005ecf61e5fd:~$ rm -rf package.json yarn.lock node_modules .cache/yarn
gibson@005ecf61e5fd:~$ yarn add lz4@0.6.3 --verbose --ignore-engines --ignore-platform --ignore-scripts --non-interactive
yarn add v1.22.1
warning package.json: No license field
verbose 0.49609171 Checking for configuration file "/home/gibson/.npmrc".
verbose 0.49775136 Checking for configuration file "/home/gibson/.npmrc".
verbose 0.499464794 Checking for configuration file "/usr/etc/npmrc".
verbose 0.500345989 Checking for configuration file "/home/gibson/.npmrc".
verbose 0.502603712 Checking for configuration file "/home/.npmrc".
verbose 0.505613409 Checking for configuration file "/home/gibson/.yarnrc".
verbose 0.506379717 Found configuration file "/home/gibson/.yarnrc".
verbose 0.508807907 Checking for configuration file "/home/gibson/.yarnrc".
verbose 0.509391676 Found configuration file "/home/gibson/.yarnrc".
verbose 0.5114413 Checking for configuration file "/usr/etc/yarnrc".
verbose 0.511893477 Checking for configuration file "/home/gibson/.yarnrc".
verbose 0.512743238 Found configuration file "/home/gibson/.yarnrc".
verbose 0.513995108 Checking for configuration file "/home/.yarnrc".
verbose 0.524608072 current time: 2020-03-08T15:35:52.984Z
warning No license field
[1/4] Resolving packages...
verbose 0.749462112 Performing "GET" request to "https://registry.yarnpkg.com/lz4".
verbose 1.645821372 Request "https://registry.yarnpkg.com/lz4" finished with status code 200.
verbose 1.677114991 Performing "GET" request to "https://registry.yarnpkg.com/buffer".
verbose 1.691640084 Performing "GET" request to "https://registry.yarnpkg.com/cuint".
verbose 1.703458945 Performing "GET" request to "https://registry.yarnpkg.com/nan".
verbose 1.71214292 Performing "GET" request to "https://registry.yarnpkg.com/xxhashjs".
verbose 1.838952352 Request "https://registry.yarnpkg.com/buffer" finished with status code 200.
verbose 1.978722299 Performing "GET" request to "https://registry.yarnpkg.com/base64-js".
verbose 1.996443625 Performing "GET" request to "https://registry.yarnpkg.com/ieee754".
verbose 2.02724696 Request "https://registry.yarnpkg.com/cuint" finished with status code 200.
verbose 2.242323291 Request "https://registry.yarnpkg.com/xxhashjs" finished with status code 200.
verbose 2.380694416 Request "https://registry.yarnpkg.com/nan" finished with status code 200.
verbose 2.42079139 Request "https://registry.yarnpkg.com/base64-js" finished with status code 200.
verbose 2.478717951 Request "https://registry.yarnpkg.com/ieee754" finished with status code 200.
[2/4] Fetching packages...
verbose 2.672529197 Performing "GET" request to "https://registry.yarnpkg.com/lz4/-/lz4-0.6.3.tgz".
verbose 2.716723 Performing "GET" request to "https://registry.yarnpkg.com/buffer/-/buffer-5.5.0.tgz".
verbose 2.741553729 Performing "GET" request to "https://registry.yarnpkg.com/xxhashjs/-/xxhashjs-0.2.2.tgz".
verbose 2.778947676 Performing "GET" request to "https://registry.yarnpkg.com/base64-js/-/base64-js-1.3.1.tgz".
verbose 2.843496736 Performing "GET" request to "https://registry.yarnpkg.com/ieee754/-/ieee754-1.1.13.tgz".
verbose 4.625124132 Error: https://registry.yarnpkg.com/lz4/-/lz4-0.6.3.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, link '/home/gibson/.cache/yarn/v6/npm-lz4-0.6.3-78df6bb69a36d7db6c2e849494876ba6e38e66d6-integrity/node_modules/lz4/build/Release/obj.target/build/Release/lz4.node' -> '/home/gibson/.cache/yarn/v6/npm-lz4-0.6.3-78df6bb69a36d7db6c2e849494876ba6e38e66d6-integrity/node_modules/lz4/build/Release/obj.target/lz4.node'"
    at MessageError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/share/yarn/lib/cli.js:750:123)
    at Extract.<anonymous> (/usr/share/yarn/lib/cli.js:63814:14)
    at Extract.emit (events.js:323:22)
    at Extract.module.exports.Extract.destroy (/usr/share/yarn/lib/cli.js:150826:17)
    at onunlock (/usr/share/yarn/lib/cli.js:150703:26)
    at stat (/usr/share/yarn/lib/cli.js:45789:23)
    at /usr/share/yarn/lib/cli.js:45815:11
    at FSReqCallback.oncomplete (fs.js:154:23)
error https://registry.yarnpkg.com/lz4/-/lz4-0.6.3.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, link '/home/gibson/.cache/yarn/v6/npm-lz4-0.6.3-78df6bb69a36d7db6c2e849494876ba6e38e66d6-integrity/node_modules/lz4/build/Release/obj.target/build/Release/lz4.node' -> '/home/gibson/.cache/yarn/v6/npm-lz4-0.6.3-78df6bb69a36d7db6c2e849494876ba6e38e66d6-integrity/node_modules/lz4/build/Release/obj.target/lz4.node'"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Downloading the tgz and attempting to extract with `tar` produces a similar error. Installing version 0.6.0 works fine.

**Comment by buu700** [comment]
Nevermind, this is a yarn problem: https://github.com/yarnpkg/yarn/issues/7212.
